#!/usr/bin/env bash
# This script configures a new Ubuntu machine to install nginx

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
STRING="rewrite ^/redirect_me/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/server_name _;/ a\ \ \ \ \ \ \ \ $STRING" /etc/nginx/sites-available/default
sudo service nginx restart
