#!/usr/bin/env bash
# This script generates a MySQL dump and creates a compressed archive out of it
mysqldump -u root --password="$1" --all-databases > backup.sql
tar -zcvf "$(date '+%d-%m-%Y').tar.gz" backup.sql