#!/usr/bin/env bash
# This script
# Creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminates itself when 
# receiving a SIGQUIT or SIGTERM signal
touch /var/run/holbertonscript.pid
FILE="/var/run/holbertonscript.pid"
echo $BASHPID >> "$FILE"
function handling
{
    signal=$1
    if [ "$signal" -eq 15 ]
        then
            echo "I hate the kill command"
            rm -f "$FILE"
            exit
    elif [ "$signal" -eq 2 ]
        then
            echo "Y U no love me?!"
    elif [ "$signal" -eq 3 ]
        then
            rm -f "$FILE"
            exit
    fi
}
trap 'handling 15' SIGTERM; trap 'handling 2' SIGINT; trap 'handling 3' SIGQUIT
while 'true'
    do
        echo "To infinity and beyond"
        sleep 2
done
