#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely
function handling
{
    echo "I am invincible!!!"
}
trap handling SIGTERM
while 'true'
    do
        echo "To infinity and beyond"
        sleep 2
done
