#!/usr/bin/env bash
#This script displays the content of the file /etc/passwd.
#username, user id, Home directory path for the user

FILE="/etc/passwd"
while read -r line;
    do
        echo  "$line" | cut -d':' -f1,3,6
done < "$FILE"
