#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd, using the while
# loop + IFS
FILE="/etc/passwd"
while IFS=: read -r USERNAME PASSWD USERID GROUPID INFO HOMEDIRECTORY COMMAND;
    do
        printf  "The user %s is part of the %s gang, lives in %s and rides %s. \
%s's place is protected by the passcode %s, more info about the user \
here: %s\n" "$USERNAME" "$GROUPID" "$HOMEDIRECTORY" "$COMMAND" "$USERID" \
"$PASSWD" "$INFO"
done < "$FILE"
